# This is a basic workflow to help you get started with Actions

name: GodotExportCI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Export game
        uses: firebelley/godot-export@v2.6.1
        with:
          # The download url of the 64 bit Linux Headless Godot executable.
          godot_executable_download_url: "https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_linux_headless.64.zip"
          # The url of the export templates corresponding to the Godot executable version.
          godot_export_templates_download_url: "https://downloads.tuxfamily.org/godotengine/3.2.3/Godot_v3.2.3-stable_export_templates.tpz"
          # The relative path containing the "project.godot" file.
          relative_project_path: "./"
          base_version: 0.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
