# This is a basic workflow to help you get started with Actions

name: GodotExportCI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get tag from version
        id: tag_version
        run: |
          echo ::set-output name=TAG_VERSION::${GITHUB_REF#refs/tags/v}
      - name: Export game
        uses: firebelley/godot-export@v2.6.1
        with:
          # The download url of the 64 bit Linux Headless Godot executable.
          godot_executable_download_url: "https://downloads.tuxfamily.org/godotengine/3.3.1/Godot_v3.3.1-stable_linux_headless.64.zip"
          # The url of the export templates corresponding to the Godot executable version.
          godot_export_templates_download_url: "https://downloads.tuxfamily.org/godotengine/3.3.1/Godot_v3.3.1-stable_export_templates.tpz"
          # The relative path containing the "project.godot" file.
          relative_project_path: "./"
          create_release: true
          base_version:  ${{ steps.tag_version.outputs.TAG_VERSION}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
